# Generated by Django 5.1 on 2024-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetalCancerRiskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('factor', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('value', models.DecimalField(decimal_places=20, max_digits=25, null=True)),
                ('is_adult', models.BooleanField(default=False, null=True)),
                ('is_cancer', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'metal_cancer_risk',
            },
        ),
        migrations.CreateModel(
            name='MetalDensityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('Cd', models.FloatField(null=True)),
                ('Pd', models.FloatField(null=True)),
                ('Cu', models.FloatField(null=True)),
                ('Zn', models.FloatField(null=True)),
                ('Ni', models.FloatField(null=True)),
                ('Cr', models.FloatField(null=True)),
                ('As', models.FloatField(null=True)),
                ('Hg', models.FloatField(null=True)),
                ('HM', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'metal_density',
            },
        ),
        migrations.CreateModel(
            name='PAHsCancerRiskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('factor', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('value', models.DecimalField(decimal_places=20, max_digits=25, null=True)),
                ('is_adult', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'PAHs_cancer_risk',
            },
        ),
        migrations.CreateModel(
            name='PAHsDensityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'PAHs_density',
            },
        ),
        migrations.CreateModel(
            name='SocialEconomyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField(null=True)),
                ('province', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('factors', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'social_economy',
            },
        ),
    ]
