# Generated by Django 5.1 on 2024-11-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceldata', '0002_metalaverageannualmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalReferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('reference_number', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'metal_reference',
            },
        ),
    ]
