# Generated by Django 5.1 on 2024-11-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceldata', '0004_remove_socialeconomymodel_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaldensitymodel',
            name='As',
        ),
        migrations.RemoveField(
            model_name='metaldensitymodel',
            name='Cd',
        ),
        migrations.RemoveField(
            model_name='metaldensitymodel',
            name='Cr',
        ),
        migrations.RemoveField(
            model_name='metaldensitymodel',
            name='Cu',
        ),
        migrations.RemoveField(
            model_name='metaldensitymodel',
            name='HM',
        ),
        migrations.RemoveField(
            model_name='metaldensitymodel',
            name='Hg',
        ),
        migrations.RemoveField(
            model_name='metaldensitymodel',
            name='Ni',
        ),
        migrations.RemoveField(
            model_name='metaldensitymodel',
            name='Pd',
        ),
        migrations.RemoveField(
            model_name='metaldensitymodel',
            name='Zn',
        ),
        migrations.AddField(
            model_name='metaldensitymodel',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='metaldensitymodel',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
