# Generated by Django 5.1 on 2024-11-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exceldata', '0005_remove_metaldensitymodel_as_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metalcancerriskmodel',
            name='factor',
        ),
    ]
