# Generated by Django 5.1 on 2024-11-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exceldata', '0006_remove_metalcancerriskmodel_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metalcancerriskmodel',
            name='is_cancer',
        ),
    ]
