# Generated by Django 5.1 on 2024-11-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceldata', '0007_remove_metalcancerriskmodel_is_cancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalNonCancerRiskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('value', models.DecimalField(decimal_places=20, max_digits=25, null=True)),
                ('is_adult', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'metal_non_cancer_risk',
            },
        ),
    ]
